### ISSUE TITLE
V1.0.0

### ISSUE THREAD

**Issue by Nukesor** [Nukesor/pueue#150]
Todos:

- [x] Get TLS up and running. #52
- [ ] ~~TLS authentication via client certificates.~~
- [x] Extract client secret into separate file to allow dotfile sharing. #137
- [x] Automatic TLS CA/cert/key creation. #52
- [x] Rename everything from `socket` to `stream`.
- [x] Clean up interface (remove `--port` `--unix-socket-path` etc.)
- [x] Exit client with non-zero when getting a failure message from the daemon.
- [x]  `--print-task-id` flag on `add` #151

Wiki: 
- [x] Adjust remote connection section to new behavior.
